### ISSUE TITLE
Add pdfs

### ISSUE THREAD

**Issue by idontgetoutmuch** [mokus0/random-fu#20]
In R one can sample e.g. from the normal distribution with rnorm and calculate the pdf and cdf at a point with dnorm and pnorm. In random-fu, we have cdf. Can we add a new class PDF(?) so that we can also have pdfs?

**Comment by rpglover64** [comment]
This issue should be closed now, right?

**Comment by idontgetoutmuch** [comment]
Well yes but I haven't given all distributions a pdf instance. I guess I should open a new issue which explicitly lists the missing pdfs and then we can add them as we implement them.
