### ISSUE TITLE
Determistic evaluation of Categorical with shuffled weights

### ISSUE THREAD

**Issue by FintanH** [mokus0/random-fu#46]
So I wonder if this is correct behaviour, granted I don't know a _whole_ lot about probability sampling. The below code uses the same seed and weighted categories, but depending on the ordering of the inputs it will choose the category non-deterministically. Is this correct?

```haskell
import Data.Random
import Data.Random.Distribution.Categorical
import Data.Random.Source.StdGen

main :: IO ()
main = do
  let ab = fromWeightedList [(75, "a"), (25 :: Double, "b")]
      ba = fromWeightedList [(25, "b"), (75 :: Double, "a")]
      seed = mkStdGen 0
  print $ sampleState ab seed
  print $ sampleState ba seed
```
```
*Main> main
("b",1601120196 1655838864)
("a",1601120196 1655838864)
```

**Comment by idontgetoutmuch** [comment]
I think it is non-deterministic full stop - if you change the seed I suspect you will get a different answer.  If you run your sampler multiple times it should give you the values of "a" and "b" in the proportions you specify. Other than that it can randomly give either value (obviously a fixed seed will give the same random result). I am going to close this but please re-open if you feel this isn't a full answer.
