### ISSUE TITLE
Bad upper bound on log-domain

### ISSUE THREAD

**Issue by adamConnerSax** [mokus0/random-fu#50]
log-domain-0.13 removed the ```log1p``` function. It's in base (as of 4.9). (https://hackage.haskell.org/package/base-4.12.0.0/docs/Numeric.html)
 
This causes a problem because log-domain 0.13 can obviously be chosen by cabal and then random-fu fails to build.  I can work around it by specifying a log-domain version <0.13 in my cabal file but it would be nice to fix it in random-fu.

**Comment by adamConnerSax** [comment]
I'd be happy to submit a PR to fix, but I'm not sure if you want to put in a correct upper bound on log-domain (<0.13) or use log1p from base and make sure base >= 0.4.9.

**Comment by idontgetoutmuch** [comment]
I don't really understand base versions so I will now go and look but I think making base >= 0.4.9 sounds the better option.

**Comment by idontgetoutmuch** [comment]
It seems that 4.9 is quite old so please submit a PR to make base >= 4.9
```
8.0.1 (May 2016)	4.9.0.0
8.0.2 (Jan 2017)	4.9.1.0
8.2.1 (Jul 2017)	4.10.0.0
8.2.2 (Nov 2017)	4.10.1.0
8.4.1 (Mar 2018)	4.11.0.0
8.4.2 (Apr 2018)	4.11.1.0
8.6.1 (August 2018)	4.12.0.0
```

**Comment by adamConnerSax** [comment]
Hopefully fully addressed by https://github.com/mokus0/random-fu/pull/51. I'll leave this for you to close if you feel it's complete.

**Comment by adamConnerSax** [comment]
Are you planning to release this fix on hackage soon?  Sorry to be a bother but the issue is causing me to have to put spurious things in cabal files all over the place.  And eventually it will cause an actual problem if anything depends on "log-domain > 0.12"

Thanks!

**Comment by idontgetoutmuch** [comment]
I can try.

**Comment by idontgetoutmuch** [comment]
https://hackage.haskell.org/package/random-fu-0.2.7.3 - let me know if you have any problems

**Comment by adamConnerSax** [comment]
Fantastic! Thanks.
