### ISSUE TITLE
rvar doesn't build with GHC-8.8.1 (MonadFail)

### ISSUE THREAD

**Issue by phadej** [mokus0/random-fu#52]
I made revision on Hackage: https://hackage.haskell.org/package/rvar-0.2.0.3/revisions/

**Comment by int-e** [comment]
This is fixed in principle by #49 but still needs a new release of `rvar`.

(I left a similar comment on that pull request, but here is the right place for it.)

**Comment by idontgetoutmuch** [comment]
Hackage is refusing to accept at the moment:

```
Uploading dist-newstyle/sdist/rvar-0.2.0.4.tar.gz...
Error uploading dist-newstyle/sdist/rvar-0.2.0.4.tar.gz: http code 400
Error: Invalid package

rvar-0.2.0.4/rvar.cabal:0:0: version with tags
```

**Comment by idontgetoutmuch** [comment]
Should be there now :)
